allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  onnxruntime-node: true
  protobufjs: false
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
