-- ════════════════════════════════════════════════════════════════════════════
-- 歌词起点：详情页自动识别署名区出错时，由后台手动指定正文从哪个时间标签开始
-- （如 '00:23.97'）。此前的行全部算署名区。留空即自动识别，绝大多数歌不用填。
-- ════════════════════════════════════════════════════════════════════════════

alter table public.temp add column lyrics_start text;
alter table public.music add column lyrics_start text;

-- ─── 审批同步：把 lyrics_start 一并从 temp 同步到 music ─────────────────────
--
-- 下面是 approve_music_sync 的函数体，只在三处加了 lyrics_start。
-- 在 Supabase 后台 Database → Functions 里编辑该函数，用它替换原函数体即可，
-- 函数签名与 security definer 等属性保持不变。
--
-- BEGIN
--   INSERT INTO public.music (
--     id, date, title, track, tracktotal, artist, lyricist,
--     composer, arranger, lyrics, lyrics_start, genre, album, albumartist, comment,
--     length, discnumber, disctotal, kugolink, type, hascover, qmlink, nelink, nmn_status, updated_at
--   )
--   SELECT
--     id, date, title, track, tracktotal, artist, lyricist,
--     composer, arranger, lyrics, lyrics_start, genre, album, albumartist, comment,
--     length, discnumber, disctotal, kugolink, type, hascover, qmlink, nelink, nmn_status, updated_at
--   FROM public.temp
--   WHERE id = temp_id
--   ON CONFLICT (id) DO UPDATE SET
--     date = EXCLUDED.date,
--     title = EXCLUDED.title,
--     track = EXCLUDED.track,
--     tracktotal = EXCLUDED.tracktotal,
--     artist = EXCLUDED.artist,
--     lyricist = EXCLUDED.lyricist,
--     composer = EXCLUDED.composer,
--     arranger = EXCLUDED.arranger,
--     lyrics = EXCLUDED.lyrics,
--     lyrics_start = EXCLUDED.lyrics_start,
--     genre = EXCLUDED.genre,
--     album = EXCLUDED.album,
--     albumartist = EXCLUDED.albumartist,
--     comment = EXCLUDED.comment,
--     length = EXCLUDED.length,
--     discnumber = EXCLUDED.discnumber,
--     disctotal = EXCLUDED.disctotal,
--     kugolink = EXCLUDED.kugolink,
--     type = EXCLUDED.type,
--     hascover = EXCLUDED.hascover,
--     qmlink = EXCLUDED.qmlink,
--     nelink = EXCLUDED.nelink,
--     nmn_status = EXCLUDED.nmn_status,
--     updated_at = EXCLUDED.updated_at;
-- END;
--
-- 另有一个 sync_music_from_temp 函数，若它同样逐列列出字段，也要照此加上 lyrics_start。
